name = "python-template"
version = "0.1.0"
description = "Stencila's RO-Crate plugin written in Python."
home = "https://github.com/LivePublication/ro-crate-plugin"
install = "git+https://github.com/LivePublication/ro-crate-plugin"
runtime = "python>=3.10"
transports = ["stdio", "http"]

# This should be an entry point defined in pyproject.toml.
command = "run_plugin"

[[kernels]]
# This should be the name that is return by "get_name" in the Kernel class.
name = "echo-python"

[[models]]
id = "stencila/echo-python"
name = "Python Echo Model"
description = "A generative model that simply echos the input messages as JSON"
